### ISSUE TITLE
How to enter Bootloader Mode after flashing Sonoff_Zigbee_Dongle_Firmware/Dongle-E/Router/Z3RouterUSBDonlge_EZNet6.10.3_V1.0.0.gbl ?

### ISSUE THREAD

**Issue by tukenmail** [itead/Sonoff_Zigbee_Dongle_Firmware#1]
How to enter Bootloader Mode after flashing Sonoff_Zigbee_Dongle_Firmware/Dongle-E/Router/Z3RouterUSBDonlge_EZNet6.10.3_V1.0.0.gbl ?
After flashing this router firmware, I can't enter Bootloader Mode through boot button.
I can't flash other firmware anymore.
Boot button is used by pair function.
Help.
Thank You.

**Comment by chasetb** [comment]
I used using the [elelabs-zigbee-ezsp-utility](https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/#restart--restart-the-connected-generic-zigbeethread-product-in-normal-ezspspinel-mode-or-in-bootloader-mode) to place my ZBDongle-E device back into Bootloader mode. It doesn't require holding down any buttons which is nice and the same utility can be used to flash firmware to the ZBDongle-E too.

**Comment by darkxst** [comment]
I have not had any issues getting into bootloader mode when flashed with router firmware. Just hold down the boot button while plugging into USB port and it will come up in the Gecko bootloader.

The Elelabs tool does not work when the ZBDongle-E has the router firmware flashed (it works perfectly with the standard firmware though), since the router firmware uses an ascii based serial shell which confuses the autodetection/probing of the device. I've not yet worked out how to get this firmware back into bootloader mode using software methods. Maybe one of the commands in the shell will allow to do this, however not found any documentation for that.

You can however use the shell to put the device back into pairing mode with the ```network leave``` command, without having to open the device to access the boot/pairing button! and there are a few other obvious commands such as ```info``` and ```version``` that return device/firmware info etc.

**Comment by tukenmail** [comment]
Hold down the boot button while plugging into USB port and it will come up in the Gecko bootloader.

It works.
Thank you.
But have to remove case.
Hope it support elelabs-zigbee-ezsp-utility in the future.

**Comment by JacekKac** [comment]
> I used using the [elelabs-zigbee-ezsp-utility](https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/#restart--restart-the-connected-generic-zigbeethread-product-in-normal-ezspspinel-mode-or-in-bootloader-mode) to place my ZBDongle-E device back into Bootloader mode. It doesn't require holding down any buttons which is nice and the same utility can be used to flash firmware to the ZBDongle-E too.

@chasetb can you help with flashin sonooff "E" dongle with this tool? nor sure how to use it in case of sonoff

**Comment by JacekKac** [comment]
ok i did it. one more question how to software reset the devic to allow new pairing?

**Comment by JacekKac** [comment]
can you provide a way to do it from a command line on unix system ? i was always using some python script to handle devices

**Comment by darkxst** [comment]
Plug into computer USB and run ```screen /dev/ttyUSB0``` (or whatever the actual device is detected as) 
then you get a shell to send the commands

**Comment by darkxst** [comment]
or use minicom or whatever serial console you have available on your distro of choice

**Comment by jvnrambo** [comment]
Dear @darkxst, I see that you know a lot, so I ask for your help to solve the following problem:
- I installed the Z3RouterUSBDonlge_EZNet6.10.3_V1.0.0.gbl firmware on a zbdongle-e, but unfortunately, for some reason that I haven't yet discovered, I can pair the door/window XIAOMI MCCGQ01LM sensors without problem, and they work for a while, but then they become unavailable after some time when paired with this router firmware, which does not happen when they are paired with the zbdongle-p with router firmware, nor when paired with the zbdongle-e as coordinator. The problem is that I have many door and window sensors for this model, and I have 3 zbdongle-e devices that I bought to be used as a router together with the zbdongle-p that I have as a coordinator. Thank you in advance for your help with the following questions: 
- 1- Do you know if there is another more current firmware to use as a router on the zbdongle-e?  
- 2 - after flashing the zbdongle-e as a router, I am unable to return the firmware of this device to coordinator firmware again, or any other firmware. I tried via tera-term, putty, ..., and I didn't succeed, can you give me any tips on how I can do this??

**Comment by darkxst** [comment]
Aqara devices are a bit non-standard and can have issues with child aging with some router firmware. I believe the ZBDongle-P router firmware includes a workaround for this, whereas dongle-E probably doesnt.

I will be adding router firmware here soon, but until then you can try nerivec's router firmware (I dont think it includes any specific Aqara fixes though. https://github.com/Nerivec/silabs-firmware-builder/releases/tag/v2024.6.2-update2


From router you can use `universal-silabs-flasher` with `--bootloader-reset sonoff` option. or open case and use boot button.

**Comment by jvnrambo** [comment]
Dear @darkxst, thanks for the tips and help. I was wondering if there might be some incompatibility between the most newest firmware versions of the coordinators I tested wich zbdongle-e and zbdongle-p, and the router's firmware. I'm going to test it by going back to an older version in coordinator to see if it solves it. I am very grateful for you making new firmware available for the router. I'm eagerly waiting to test it, because as I said I have a lot of door/windows sensors from this xiaomi model, and 3 zbdongle-e to put into use, and I need to make these devices compatible.

**Comment by jvnrambo** [comment]
Dear @darkxst, I installed the sonoff zbdongle zigbee router 8.0.2.0_115200_sw_flow.gbl firmware on the zbdongle-e, and then started the dongle, but it does not enter pairing mode. I connected via tera term and the terminal doesn't display anything, it stays black, with no option to use a command "network leave" to put the dongle in pairing mode.

**Comment by jvnrambo** [comment]
I had successfully paired the zbdongle-e with the zha with this router firmware that you suggested. I share so that other users who have the same problem know that the Xiaomi door/window sensor devices no longer lose connection using this firmware, as happened with the Z3RouterUSBDonlge_EZNet6.10.3_V1.0.0.gbl firmware. Thank you @darkxst for your time and help.
